export const LOAD_CHANNELS = 'LOAD_CHANNELS'
export const ADD_CHANNEL = 'ADD_CHANNEL'
export const DELETE_CHANNEL = 'DELETE_CHANNEL'
export const EDIT_CHANNEL = 'EDIT_CHANNEL'

export const EDIT_CURRENT_CHANNEL_NAME = 'EDIT_CURRENT_CHANNEL_NAME'
export const EDIT_CURRENT_CHANNEL_IPLIST = 'EDIT_CURRENT_CHANNEL_IPLIST'
export const CLEAR_CURRENT_CHANNEL = 'CLEAR_CURRENT_CHANNEL'
export const REPLACE_CURRENT_CHANNEL = 'REPLACE_CURRENT_CHANNEL'

export const START_CHANNEL = 'START_CHANNEL'
export const STOP_CHANNEL = 'STOP_CHANNEL'
export const START_ALL_CHANNELS = 'START_ALL_CHANNELS'
export const STOP_ALL_CHANNELS = 'STOP_ALL_CHANNELS'
